config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :work_orders
  resources :equipment
  resources :employees
  resources :search

  root 'landings#secure'
  get 'secure' => 'landings#secure'




#                   Prefix Verb   URI Pattern                     Controller#Action
#         new_user_session GET    /users/sign_in(.:format)        devise/sessions#new
#             user_session POST   /users/sign_in(.:format)        devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)       devise/sessions#destroy
#            user_password POST   /users/password(.:format)       devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)   devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)  devise/passwords#edit
#                          PATCH  /users/password(.:format)       devise/passwords#update
#                          PUT    /users/password(.:format)       devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)         devise/registrations#cancel
#        user_registration POST   /users(.:format)                devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)        devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)           devise/registrations#edit
#                          PATCH  /users(.:format)                devise/registrations#update
#                          PUT    /users(.:format)                devise/registrations#update
#                          DELETE /users(.:format)                devise/registrations#destroy
#              work_orders GET    /work_orders(.:format)          work_orders#index
#                          POST   /work_orders(.:format)          work_orders#create
#           new_work_order GET    /work_orders/new(.:format)      work_orders#new
#          edit_work_order GET    /work_orders/:id/edit(.:format) work_orders#edit
#               work_order GET    /work_orders/:id(.:format)      work_orders#show
#                          PATCH  /work_orders/:id(.:format)      work_orders#update
#                          PUT    /work_orders/:id(.:format)      work_orders#update
#                          DELETE /work_orders/:id(.:format)      work_orders#destroy
#          equipment_index GET    /equipment(.:format)            equipment#index
#                          POST   /equipment(.:format)            equipment#create
#            new_equipment GET    /equipment/new(.:format)        equipment#new
#           edit_equipment GET    /equipment/:id/edit(.:format)   equipment#edit
#                equipment GET    /equipment/:id(.:format)        equipment#show
#                          PATCH  /equipment/:id(.:format)        equipment#update
#                          PUT    /equipment/:id(.:format)        equipment#update
#                          DELETE /equipment/:id(.:format)        equipment#destroy
#                employees GET    /employees(.:format)            employees#index
#                          POST   /employees(.:format)            employees#create
#             new_employee GET    /employees/new(.:format)        employees#new
#            edit_employee GET    /employees/:id/edit(.:format)   employees#edit
#                 employee GET    /employees/:id(.:format)        employees#show
#                          PATCH  /employees/:id(.:format)        employees#update
#                          PUT    /employees/:id(.:format)        employees#update
#                          DELETE /employees/:id(.:format)        employees#destroy
#                     root GET    /                               landings#secure
#                   secure GET    /secure(.:format)               landings#secure

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :work_orders
end

app/controllers/employees_controller.rb
class EmployeesController <ApplicationController 
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  
  def index
    @employee = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.employee_id
      @employee.employee_id = @employee.employee_id
    end

    if @employee.save
      redirect_to @employee
    else
      render :action => :new
    end
  end
 
  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      redirect_to @employee
    else
      render :action => :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path
  end

  private

    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :employee_id)
    end


end

app/views/employees/_form.html.erb
  <%= form_for @employee do |form| %>
  Name: <%= form.text_field :first_name %>
  <%= form.text_field :last_name %>
  Badge Number: <%= form.text_field :employee_id %> <br>
   <%= form.submit %>
<% end %>

app/views/employees/edit.html.erb
<h1>Employee Edit</h1>

<% if user_signed_in? %>
  <%= render :partial => 'form' %>
  <% else %>
  <h2>You must be signed in to view this page.</h2>
<% end -%>

app/views/employees/index.html.erb
<h1>Employees Index</h1>

<% i = 0 %>
<% @employee.each do |employee| %>
<% i += 1 %>
  <table class="table">
    <tr >
      <th scope="row"><%= i %>.</th>
      <td><%= employee.last_name %>, <%= employee.first_name %> </td>
      <td><%= employee.employee_id %></td>
      <td>
        <%= link_to 'View', employee_path(employee.id) %>
        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_employee_path(employee.id) %>
          <%= link_to 'Delete', employee, :method => 'delete' %>
        <% end -%>
      </td>
    </tr><br>
  </table>
 <% end %>

<% if user_signed_in? %>
<p><%= link_to 'New employee', new_employee_path %> </p>
<% end -%>

app/views/employees/new.html.erb
<h1>Employee New</h1>

<% if user_signed_in? %>
  <%= render :partial => 'form' %>
  <% else %>
  <h2>You must be signed in to view this page.</h2>
<% end -%>

app/views/employees/show.html.erb
<h1>Technicians Show</h1>
<div> <%= @employee[:first_name] %> <%= @employee[:last_name] %> </div>
<div> <%= @employee[:employee_id] %> </div>

<% if user_signed_in? %>
<h1>add delete and edit paths</h1>
<% end -%>