config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :work_orders
  resources :equipment
  resources :employees
  resources :search

  root 'landings#secure'
  get 'secure' => 'landings#secure'




#                   Prefix Verb   URI Pattern                     Controller#Action
#         new_user_session GET    /users/sign_in(.:format)        devise/sessions#new
#             user_session POST   /users/sign_in(.:format)        devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)       devise/sessions#destroy
#            user_password POST   /users/password(.:format)       devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)   devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)  devise/passwords#edit
#                          PATCH  /users/password(.:format)       devise/passwords#update
#                          PUT    /users/password(.:format)       devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)         devise/registrations#cancel
#        user_registration POST   /users(.:format)                devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)        devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)           devise/registrations#edit
#                          PATCH  /users(.:format)                devise/registrations#update
#                          PUT    /users(.:format)                devise/registrations#update
#                          DELETE /users(.:format)                devise/registrations#destroy
#              work_orders GET    /work_orders(.:format)          work_orders#index
#                          POST   /work_orders(.:format)          work_orders#create
#           new_work_order GET    /work_orders/new(.:format)      work_orders#new
#          edit_work_order GET    /work_orders/:id/edit(.:format) work_orders#edit
#               work_order GET    /work_orders/:id(.:format)      work_orders#show
#                          PATCH  /work_orders/:id(.:format)      work_orders#update
#                          PUT    /work_orders/:id(.:format)      work_orders#update
#                          DELETE /work_orders/:id(.:format)      work_orders#destroy
#          equipment_index GET    /equipment(.:format)            equipment#index
#                          POST   /equipment(.:format)            equipment#create
#            new_equipment GET    /equipment/new(.:format)        equipment#new
#           edit_equipment GET    /equipment/:id/edit(.:format)   equipment#edit
#                equipment GET    /equipment/:id(.:format)        equipment#show
#                          PATCH  /equipment/:id(.:format)        equipment#update
#                          PUT    /equipment/:id(.:format)        equipment#update
#                          DELETE /equipment/:id(.:format)        equipment#destroy
#                employees GET    /employees(.:format)            employees#index
#                          POST   /employees(.:format)            employees#create
#             new_employee GET    /employees/new(.:format)        employees#new
#            edit_employee GET    /employees/:id/edit(.:format)   employees#edit
#                 employee GET    /employees/:id(.:format)        employees#show
#                          PATCH  /employees/:id(.:format)        employees#update
#                          PUT    /employees/:id(.:format)        employees#update
#                          DELETE /employees/:id(.:format)        employees#destroy
#                     root GET    /                               landings#secure
#                   secure GET    /secure(.:format)               landings#secure

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  belongs_to :work_orders
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController 
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  def index
    @equipment = Equipment.all
  end

  def show
    @equipment = Equipment.find(params[:id])
  end

  def new
    @equipment = Equipment.new
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def create
    @equipment = Equipment.new(equipment_params)

    if @equipment.id_number
      @equipment.id_number = @equipment.id_number
    end

    if @equipment.save
      redirect_to @equipment
    else 
      render :action => :new
    end
  end

  def update
    @equipment = Equipment.find(params[:id])
    @equipment.update_attributes(equipment)
    redirect_to equipment.path

    if @equipment.update(equipment_params)
      redirect_to @equipment
    else
      render :action => :edit
    end
  end

  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy
    redirect_to @equipment
  end

private 

  def set_equipment
    @equipment = Equipment.find(params[:id])
  end

  def equipment_params
      params.require(:equipment).permit(:name, :id_number, :condition, :checked_out, :notes, :quantity)
  end

end

app/controllers/equipments_controller.rb
class EquipmentsController <ApplicationController 

  def index
    @equipment = Equipment.all
  end

  def create
    @equipment = Equipment.find(params[:id])
  end

  def new
    @equipment = Equipment.new
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def show
    @equipment = Equipment.find(params[:id])
  end

  def update
    @equipment = Equipment.find(params[:id])
    @equipment.update_attributes(equipment)
    redirect_to equipment.path

    if @equipment.update(equipment_params)
      redirect_to @equipment
    else
      render :action => :edit
    end
  end

  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy
    redirect_to equipments_path
  end


end

app/views/equipment/_form.html.erb
<%= form_for @equipment do |form| %>
  Name: <%= form.text_field :name %></br>
  ID: <%= form.text_field :id_number %></br>
  Condition: <%= form.text_field :condition %></br>
  Quantity: <%= form.text_field :quantity %></br>
  Notes: <%= form.text_area :notes %></br>
  <%= form.submit %>
<% end %>

app/views/equipment/edit.html.erb
<h1>Equipment Edit</h1>

<% if user_signed_in? %>
  <%= render :partial => 'form' %>
  <% else %>
  <h2>You must be signed in to view this page.</h2>
<% end -%>

app/views/equipment/index.html.erb
<h1>Equipment Index</h1>

<% i = 0 %>
<% @equipment.each do |equipment| %>
  <% i += 1 %>
  <table>
    <tr class="table">
     <th scope="row"><%= i %>.</th scope="row">
         <td><%= equipment.name %></td> 
         <td>
            <%= link_to 'View', equipment_path(equipment.id) %>
            <% if user_signed_in? %>
                <%= link_to 'Edit', edit_equipment_path(equipment.id) %>
                <%= link_to 'Delete', equipment, :method => 'delete' %>
            <% end -%>
         </td>
    </tr><br>
</table>
<% end %>

<% if user_signed_in? %>
    <p><%= link_to 'Add Equipment', new_equipment_path %></p>
<% end -%>

app/views/equipment/new.html.erb
<h1>Equipment New</h1>

<% if user_signed_in? %>
  <%= render :partial => 'form' %>
  <% else %>
  <h2>You must be signed in to view this page.</h2>
<% end -%>

app/views/equipment/show.html.erb
<h1>Equipment Show</h1>
<div><%= @equipment[:name] %> </div>
<div>ID Number: <%= @equipment[:id_number] %></div>
<div>Condition: <%= @equipment[:condition] %></div>
<div>Checked Out: <%= @equipment[:checked_out] %>, <%= @equipment[:location] %></div>
<div>Notes: <%= @equipment[:notes] %></div>

<% if user_signed_in? %>
<h1>Add links to edit and delete</h1>
<% end -%>