config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :work_orders
  resources :equipment
  resources :employees
  resources :search

  root 'landings#secure'
  get 'secure' => 'landings#secure'




#                   Prefix Verb   URI Pattern                     Controller#Action
#         new_user_session GET    /users/sign_in(.:format)        devise/sessions#new
#             user_session POST   /users/sign_in(.:format)        devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)       devise/sessions#destroy
#            user_password POST   /users/password(.:format)       devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)   devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)  devise/passwords#edit
#                          PATCH  /users/password(.:format)       devise/passwords#update
#                          PUT    /users/password(.:format)       devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)         devise/registrations#cancel
#        user_registration POST   /users(.:format)                devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)        devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)           devise/registrations#edit
#                          PATCH  /users(.:format)                devise/registrations#update
#                          PUT    /users(.:format)                devise/registrations#update
#                          DELETE /users(.:format)                devise/registrations#destroy
#              work_orders GET    /work_orders(.:format)          work_orders#index
#                          POST   /work_orders(.:format)          work_orders#create
#           new_work_order GET    /work_orders/new(.:format)      work_orders#new
#          edit_work_order GET    /work_orders/:id/edit(.:format) work_orders#edit
#               work_order GET    /work_orders/:id(.:format)      work_orders#show
#                          PATCH  /work_orders/:id(.:format)      work_orders#update
#                          PUT    /work_orders/:id(.:format)      work_orders#update
#                          DELETE /work_orders/:id(.:format)      work_orders#destroy
#          equipment_index GET    /equipment(.:format)            equipment#index
#                          POST   /equipment(.:format)            equipment#create
#            new_equipment GET    /equipment/new(.:format)        equipment#new
#           edit_equipment GET    /equipment/:id/edit(.:format)   equipment#edit
#                equipment GET    /equipment/:id(.:format)        equipment#show
#                          PATCH  /equipment/:id(.:format)        equipment#update
#                          PUT    /equipment/:id(.:format)        equipment#update
#                          DELETE /equipment/:id(.:format)        equipment#destroy
#                employees GET    /employees(.:format)            employees#index
#                          POST   /employees(.:format)            employees#create
#             new_employee GET    /employees/new(.:format)        employees#new
#            edit_employee GET    /employees/:id/edit(.:format)   employees#edit
#                 employee GET    /employees/:id(.:format)        employees#show
#                          PATCH  /employees/:id(.:format)        employees#update
#                          PUT    /employees/:id(.:format)        employees#update
#                          DELETE /employees/:id(.:format)        employees#destroy
#                     root GET    /                               landings#secure
#                   secure GET    /secure(.:format)               landings#secure

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p>
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <a href="../">Home</a> |
    <a href="../work_orders">Work Orders</a> |
    <a href="../work_orders/new">New Work Order</a> |
    <a href="../equipment">Equipment List</a> |
    <a href="../employees">Technicians</a> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

  </div><br>  
</nav>
  Logged in as <strong><%= current_user.email %></strong>.
  
  <%= form_tag(work_orders_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
<%= submit_tag "Search" %>
<% end %>

<% if @work_orders.present? %>
  <%= render @work_orders %>
<% else %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>


<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<%= yield %>

</body>
</html>